login_actions = [
["go_url", "https://moneyforward.com/me"],
["click", """//*[@id="new-before-login-home"]/div[1]/div[1]/p[1]/a"""],
["fill", """//*[@id="mfid_user[email]"]""", "ENV_EMAIL"],
["click", """//*[@id="submitto"]"""],
["fill", """//*[@id="mfid_user[password]"]""", "ENV_PASS"],
["click", """//*[@id="submitto"]"""],
["fill_otp", """//*[@id="otp_attempt"]""", "ENV_OTP"],
["click", """//*[@id="submitto"]"""],
]

